merge: merge.cpp
	g++ merge.cpp poly2tri/sweep/cdt.cc poly2tri/sweep/advancing_front.cc poly2tri/sweep/sweep_context.cc poly2tri/sweep/sweep.cc poly2tri/common/shapes.cc -o merge  -I/Users/stavbraun/cloudlab/build/deps/boost_1_54_0
