-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/message"

local exports = {}



local MODELDATA = protobuf.Descriptor();
local MODELDATA_MESHES_FIELD = protobuf.FieldDescriptor();
local MODELDATA_MATERIALS_FIELD = protobuf.FieldDescriptor();
local MESHDATA = protobuf.Descriptor();
local MESHDATA_NAME_FIELD = protobuf.FieldDescriptor();
local MESHDATA_VERTICES_FIELD = protobuf.FieldDescriptor();
local MESHDATA_UVS_FIELD = protobuf.FieldDescriptor();
local MESHDATA_NORMALS_FIELD = protobuf.FieldDescriptor();
local MESHDATA_SUBMESHES_FIELD = protobuf.FieldDescriptor();
local SUBMESH = protobuf.Descriptor();
local SUBMESH_MATERIALNAME_FIELD = protobuf.FieldDescriptor();
local SUBMESH_TRIANGLES_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA = protobuf.Descriptor();
local MATERIALDATA_NAME_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_AMBIENT_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_DIFFUSE_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_SPECULAR_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_SHININESS_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_ALPHA_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_ILLUMTYPE_FIELD = protobuf.FieldDescriptor();
local MATERIALDATA_DIFFUSETEXPATH_FIELD = protobuf.FieldDescriptor();

local VECTOR3 = protobuf.Descriptor();
local VECTOR3_X_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Y_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Z_FIELD = protobuf.FieldDescriptor();
local VECTOR2 = protobuf.Descriptor();
local VECTOR2_X_FIELD = protobuf.FieldDescriptor();
local VECTOR2_Y_FIELD = protobuf.FieldDescriptor();
local COLOR = protobuf.Descriptor();
local COLOR_R_FIELD = protobuf.FieldDescriptor();
local COLOR_G_FIELD = protobuf.FieldDescriptor();
local COLOR_B_FIELD = protobuf.FieldDescriptor();
local COLOR_A_FIELD = protobuf.FieldDescriptor();


MODELDATA_MESHES_FIELD.name = "meshes"
MODELDATA_MESHES_FIELD.full_name = ".PolyBox.ModelData.meshes"
MODELDATA_MESHES_FIELD.number = 1
MODELDATA_MESHES_FIELD.index = 0
MODELDATA_MESHES_FIELD.label = 3
MODELDATA_MESHES_FIELD.has_default_value = false
MODELDATA_MESHES_FIELD.default_value = {}
MODELDATA_MESHES_FIELD.message_type = MESHDATA
MODELDATA_MESHES_FIELD.type = 11
MODELDATA_MESHES_FIELD.cpp_type = 10

MODELDATA_MATERIALS_FIELD.name = "materials"
MODELDATA_MATERIALS_FIELD.full_name = ".PolyBox.ModelData.materials"
MODELDATA_MATERIALS_FIELD.number = 2
MODELDATA_MATERIALS_FIELD.index = 1
MODELDATA_MATERIALS_FIELD.label = 3
MODELDATA_MATERIALS_FIELD.has_default_value = false
MODELDATA_MATERIALS_FIELD.default_value = {}
MODELDATA_MATERIALS_FIELD.message_type = MATERIALDATA
MODELDATA_MATERIALS_FIELD.type = 11
MODELDATA_MATERIALS_FIELD.cpp_type = 10

MODELDATA.name = "ModelData"
MODELDATA.full_name = ".PolyBox.ModelData"
MODELDATA.nested_types = {}
MODELDATA.enum_types = {}
MODELDATA.fields = {MODELDATA_MESHES_FIELD, MODELDATA_MATERIALS_FIELD}
MODELDATA.is_extendable = false
MODELDATA.extensions = {}
MESHDATA_NAME_FIELD.name = "name"
MESHDATA_NAME_FIELD.full_name = ".PolyBox.MeshData.name"
MESHDATA_NAME_FIELD.number = 1
MESHDATA_NAME_FIELD.index = 0
MESHDATA_NAME_FIELD.label = 1
MESHDATA_NAME_FIELD.has_default_value = false
MESHDATA_NAME_FIELD.default_value = ""
MESHDATA_NAME_FIELD.type = 9
MESHDATA_NAME_FIELD.cpp_type = 9

MESHDATA_VERTICES_FIELD.name = "vertices"
MESHDATA_VERTICES_FIELD.full_name = ".PolyBox.MeshData.vertices"
MESHDATA_VERTICES_FIELD.number = 2
MESHDATA_VERTICES_FIELD.index = 1
MESHDATA_VERTICES_FIELD.label = 3
MESHDATA_VERTICES_FIELD.has_default_value = false
MESHDATA_VERTICES_FIELD.default_value = {}
MESHDATA_VERTICES_FIELD.message_type = VECTOR3
MESHDATA_VERTICES_FIELD.type = 11
MESHDATA_VERTICES_FIELD.cpp_type = 10

MESHDATA_UVS_FIELD.name = "uvs"
MESHDATA_UVS_FIELD.full_name = ".PolyBox.MeshData.uvs"
MESHDATA_UVS_FIELD.number = 3
MESHDATA_UVS_FIELD.index = 2
MESHDATA_UVS_FIELD.label = 3
MESHDATA_UVS_FIELD.has_default_value = false
MESHDATA_UVS_FIELD.default_value = {}
MESHDATA_UVS_FIELD.message_type = VECTOR2
MESHDATA_UVS_FIELD.type = 11
MESHDATA_UVS_FIELD.cpp_type = 10

MESHDATA_NORMALS_FIELD.name = "normals"
MESHDATA_NORMALS_FIELD.full_name = ".PolyBox.MeshData.normals"
MESHDATA_NORMALS_FIELD.number = 4
MESHDATA_NORMALS_FIELD.index = 3
MESHDATA_NORMALS_FIELD.label = 3
MESHDATA_NORMALS_FIELD.has_default_value = false
MESHDATA_NORMALS_FIELD.default_value = {}
MESHDATA_NORMALS_FIELD.message_type = VECTOR3
MESHDATA_NORMALS_FIELD.type = 11
MESHDATA_NORMALS_FIELD.cpp_type = 10

MESHDATA_SUBMESHES_FIELD.name = "submeshes"
MESHDATA_SUBMESHES_FIELD.full_name = ".PolyBox.MeshData.submeshes"
MESHDATA_SUBMESHES_FIELD.number = 5
MESHDATA_SUBMESHES_FIELD.index = 4
MESHDATA_SUBMESHES_FIELD.label = 3
MESHDATA_SUBMESHES_FIELD.has_default_value = false
MESHDATA_SUBMESHES_FIELD.default_value = {}
MESHDATA_SUBMESHES_FIELD.message_type = SUBMESH
MESHDATA_SUBMESHES_FIELD.type = 11
MESHDATA_SUBMESHES_FIELD.cpp_type = 10

MESHDATA.name = "MeshData"
MESHDATA.full_name = ".PolyBox.MeshData"
MESHDATA.nested_types = {}
MESHDATA.enum_types = {}
MESHDATA.fields = {MESHDATA_NAME_FIELD, MESHDATA_VERTICES_FIELD, MESHDATA_UVS_FIELD, MESHDATA_NORMALS_FIELD, MESHDATA_SUBMESHES_FIELD}
MESHDATA.is_extendable = false
MESHDATA.extensions = {}
SUBMESH_MATERIALNAME_FIELD.name = "materialName"
SUBMESH_MATERIALNAME_FIELD.full_name = ".PolyBox.SubMesh.materialName"
SUBMESH_MATERIALNAME_FIELD.number = 1
SUBMESH_MATERIALNAME_FIELD.index = 0
SUBMESH_MATERIALNAME_FIELD.label = 1
SUBMESH_MATERIALNAME_FIELD.has_default_value = false
SUBMESH_MATERIALNAME_FIELD.default_value = ""
SUBMESH_MATERIALNAME_FIELD.type = 9
SUBMESH_MATERIALNAME_FIELD.cpp_type = 9

SUBMESH_TRIANGLES_FIELD.name = "triangles"
SUBMESH_TRIANGLES_FIELD.full_name = ".PolyBox.SubMesh.triangles"
SUBMESH_TRIANGLES_FIELD.number = 2
SUBMESH_TRIANGLES_FIELD.index = 1
SUBMESH_TRIANGLES_FIELD.label = 3
SUBMESH_TRIANGLES_FIELD.has_default_value = false
SUBMESH_TRIANGLES_FIELD.default_value = {}
SUBMESH_TRIANGLES_FIELD.type = 5
SUBMESH_TRIANGLES_FIELD.cpp_type = 1

SUBMESH.name = "SubMesh"
SUBMESH.full_name = ".PolyBox.SubMesh"
SUBMESH.nested_types = {}
SUBMESH.enum_types = {}
SUBMESH.fields = {SUBMESH_MATERIALNAME_FIELD, SUBMESH_TRIANGLES_FIELD}
SUBMESH.is_extendable = false
SUBMESH.extensions = {}
MATERIALDATA_NAME_FIELD.name = "name"
MATERIALDATA_NAME_FIELD.full_name = ".PolyBox.MaterialData.name"
MATERIALDATA_NAME_FIELD.number = 1
MATERIALDATA_NAME_FIELD.index = 0
MATERIALDATA_NAME_FIELD.label = 1
MATERIALDATA_NAME_FIELD.has_default_value = false
MATERIALDATA_NAME_FIELD.default_value = ""
MATERIALDATA_NAME_FIELD.type = 9
MATERIALDATA_NAME_FIELD.cpp_type = 9

MATERIALDATA_AMBIENT_FIELD.name = "ambient"
MATERIALDATA_AMBIENT_FIELD.full_name = ".PolyBox.MaterialData.ambient"
MATERIALDATA_AMBIENT_FIELD.number = 2
MATERIALDATA_AMBIENT_FIELD.index = 1
MATERIALDATA_AMBIENT_FIELD.label = 1
MATERIALDATA_AMBIENT_FIELD.has_default_value = false
MATERIALDATA_AMBIENT_FIELD.default_value = nil
MATERIALDATA_AMBIENT_FIELD.message_type = COLOR
MATERIALDATA_AMBIENT_FIELD.type = 11
MATERIALDATA_AMBIENT_FIELD.cpp_type = 10

MATERIALDATA_DIFFUSE_FIELD.name = "diffuse"
MATERIALDATA_DIFFUSE_FIELD.full_name = ".PolyBox.MaterialData.diffuse"
MATERIALDATA_DIFFUSE_FIELD.number = 3
MATERIALDATA_DIFFUSE_FIELD.index = 2
MATERIALDATA_DIFFUSE_FIELD.label = 1
MATERIALDATA_DIFFUSE_FIELD.has_default_value = false
MATERIALDATA_DIFFUSE_FIELD.default_value = nil
MATERIALDATA_DIFFUSE_FIELD.message_type = COLOR
MATERIALDATA_DIFFUSE_FIELD.type = 11
MATERIALDATA_DIFFUSE_FIELD.cpp_type = 10

MATERIALDATA_SPECULAR_FIELD.name = "specular"
MATERIALDATA_SPECULAR_FIELD.full_name = ".PolyBox.MaterialData.specular"
MATERIALDATA_SPECULAR_FIELD.number = 4
MATERIALDATA_SPECULAR_FIELD.index = 3
MATERIALDATA_SPECULAR_FIELD.label = 1
MATERIALDATA_SPECULAR_FIELD.has_default_value = false
MATERIALDATA_SPECULAR_FIELD.default_value = nil
MATERIALDATA_SPECULAR_FIELD.message_type = COLOR
MATERIALDATA_SPECULAR_FIELD.type = 11
MATERIALDATA_SPECULAR_FIELD.cpp_type = 10

MATERIALDATA_SHININESS_FIELD.name = "shininess"
MATERIALDATA_SHININESS_FIELD.full_name = ".PolyBox.MaterialData.shininess"
MATERIALDATA_SHININESS_FIELD.number = 5
MATERIALDATA_SHININESS_FIELD.index = 4
MATERIALDATA_SHININESS_FIELD.label = 1
MATERIALDATA_SHININESS_FIELD.has_default_value = false
MATERIALDATA_SHININESS_FIELD.default_value = 0.0
MATERIALDATA_SHININESS_FIELD.type = 2
MATERIALDATA_SHININESS_FIELD.cpp_type = 6

MATERIALDATA_ALPHA_FIELD.name = "alpha"
MATERIALDATA_ALPHA_FIELD.full_name = ".PolyBox.MaterialData.alpha"
MATERIALDATA_ALPHA_FIELD.number = 6
MATERIALDATA_ALPHA_FIELD.index = 5
MATERIALDATA_ALPHA_FIELD.label = 1
MATERIALDATA_ALPHA_FIELD.has_default_value = false
MATERIALDATA_ALPHA_FIELD.default_value = 0.0
MATERIALDATA_ALPHA_FIELD.type = 2
MATERIALDATA_ALPHA_FIELD.cpp_type = 6

MATERIALDATA_ILLUMTYPE_FIELD.name = "illumType"
MATERIALDATA_ILLUMTYPE_FIELD.full_name = ".PolyBox.MaterialData.illumType"
MATERIALDATA_ILLUMTYPE_FIELD.number = 7
MATERIALDATA_ILLUMTYPE_FIELD.index = 6
MATERIALDATA_ILLUMTYPE_FIELD.label = 1
MATERIALDATA_ILLUMTYPE_FIELD.has_default_value = false
MATERIALDATA_ILLUMTYPE_FIELD.default_value = 0
MATERIALDATA_ILLUMTYPE_FIELD.type = 5
MATERIALDATA_ILLUMTYPE_FIELD.cpp_type = 1

MATERIALDATA_DIFFUSETEXPATH_FIELD.name = "diffuseTexPath"
MATERIALDATA_DIFFUSETEXPATH_FIELD.full_name = ".PolyBox.MaterialData.diffuseTexPath"
MATERIALDATA_DIFFUSETEXPATH_FIELD.number = 8
MATERIALDATA_DIFFUSETEXPATH_FIELD.index = 7
MATERIALDATA_DIFFUSETEXPATH_FIELD.label = 1
MATERIALDATA_DIFFUSETEXPATH_FIELD.has_default_value = false
MATERIALDATA_DIFFUSETEXPATH_FIELD.default_value = ""
MATERIALDATA_DIFFUSETEXPATH_FIELD.type = 9
MATERIALDATA_DIFFUSETEXPATH_FIELD.cpp_type = 9

MATERIALDATA.name = "MaterialData"
MATERIALDATA.full_name = ".PolyBox.MaterialData"
MATERIALDATA.nested_types = {}
MATERIALDATA.enum_types = {}
MATERIALDATA.fields = {MATERIALDATA_NAME_FIELD, MATERIALDATA_AMBIENT_FIELD, MATERIALDATA_DIFFUSE_FIELD, MATERIALDATA_SPECULAR_FIELD, MATERIALDATA_SHININESS_FIELD, MATERIALDATA_ALPHA_FIELD, MATERIALDATA_ILLUMTYPE_FIELD, MATERIALDATA_DIFFUSETEXPATH_FIELD}
MATERIALDATA.is_extendable = false
MATERIALDATA.extensions = {}


VECTOR3_X_FIELD.name = "x"
VECTOR3_X_FIELD.full_name = ".UnityEngine.Vector3.x"
VECTOR3_X_FIELD.number = 1
VECTOR3_X_FIELD.index = 0
VECTOR3_X_FIELD.label = 1
VECTOR3_X_FIELD.has_default_value = false
VECTOR3_X_FIELD.default_value = 0.0
VECTOR3_X_FIELD.type = 2
VECTOR3_X_FIELD.cpp_type = 6

VECTOR3_Y_FIELD.name = "y"
VECTOR3_Y_FIELD.full_name = ".UnityEngine.Vector3.y"
VECTOR3_Y_FIELD.number = 2
VECTOR3_Y_FIELD.index = 1
VECTOR3_Y_FIELD.label = 1
VECTOR3_Y_FIELD.has_default_value = false
VECTOR3_Y_FIELD.default_value = 0.0
VECTOR3_Y_FIELD.type = 2
VECTOR3_Y_FIELD.cpp_type = 6

VECTOR3_Z_FIELD.name = "z"
VECTOR3_Z_FIELD.full_name = ".UnityEngine.Vector3.z"
VECTOR3_Z_FIELD.number = 3
VECTOR3_Z_FIELD.index = 2
VECTOR3_Z_FIELD.label = 1
VECTOR3_Z_FIELD.has_default_value = false
VECTOR3_Z_FIELD.default_value = 0.0
VECTOR3_Z_FIELD.type = 2
VECTOR3_Z_FIELD.cpp_type = 6

VECTOR3.name = "Vector3"
VECTOR3.full_name = ".UnityEngine.Vector3"
VECTOR3.nested_types = {}
VECTOR3.enum_types = {}
VECTOR3.fields = {VECTOR3_X_FIELD, VECTOR3_Y_FIELD, VECTOR3_Z_FIELD}
VECTOR3.is_extendable = false
VECTOR3.extensions = {}
VECTOR2_X_FIELD.name = "x"
VECTOR2_X_FIELD.full_name = ".UnityEngine.Vector2.x"
VECTOR2_X_FIELD.number = 1
VECTOR2_X_FIELD.index = 0
VECTOR2_X_FIELD.label = 1
VECTOR2_X_FIELD.has_default_value = false
VECTOR2_X_FIELD.default_value = 0.0
VECTOR2_X_FIELD.type = 2
VECTOR2_X_FIELD.cpp_type = 6

VECTOR2_Y_FIELD.name = "y"
VECTOR2_Y_FIELD.full_name = ".UnityEngine.Vector2.y"
VECTOR2_Y_FIELD.number = 2
VECTOR2_Y_FIELD.index = 1
VECTOR2_Y_FIELD.label = 1
VECTOR2_Y_FIELD.has_default_value = false
VECTOR2_Y_FIELD.default_value = 0.0
VECTOR2_Y_FIELD.type = 2
VECTOR2_Y_FIELD.cpp_type = 6

VECTOR2.name = "Vector2"
VECTOR2.full_name = ".UnityEngine.Vector2"
VECTOR2.nested_types = {}
VECTOR2.enum_types = {}
VECTOR2.fields = {VECTOR2_X_FIELD, VECTOR2_Y_FIELD}
VECTOR2.is_extendable = false
VECTOR2.extensions = {}
COLOR_R_FIELD.name = "r"
COLOR_R_FIELD.full_name = ".UnityEngine.Color.r"
COLOR_R_FIELD.number = 1
COLOR_R_FIELD.index = 0
COLOR_R_FIELD.label = 1
COLOR_R_FIELD.has_default_value = false
COLOR_R_FIELD.default_value = 0.0
COLOR_R_FIELD.type = 2
COLOR_R_FIELD.cpp_type = 6

COLOR_G_FIELD.name = "g"
COLOR_G_FIELD.full_name = ".UnityEngine.Color.g"
COLOR_G_FIELD.number = 2
COLOR_G_FIELD.index = 1
COLOR_G_FIELD.label = 1
COLOR_G_FIELD.has_default_value = false
COLOR_G_FIELD.default_value = 0.0
COLOR_G_FIELD.type = 2
COLOR_G_FIELD.cpp_type = 6

COLOR_B_FIELD.name = "b"
COLOR_B_FIELD.full_name = ".UnityEngine.Color.b"
COLOR_B_FIELD.number = 3
COLOR_B_FIELD.index = 2
COLOR_B_FIELD.label = 1
COLOR_B_FIELD.has_default_value = false
COLOR_B_FIELD.default_value = 0.0
COLOR_B_FIELD.type = 2
COLOR_B_FIELD.cpp_type = 6

COLOR_A_FIELD.name = "a"
COLOR_A_FIELD.full_name = ".UnityEngine.Color.a"
COLOR_A_FIELD.number = 4
COLOR_A_FIELD.index = 3
COLOR_A_FIELD.label = 1
COLOR_A_FIELD.has_default_value = false
COLOR_A_FIELD.default_value = 0.0
COLOR_A_FIELD.type = 2
COLOR_A_FIELD.cpp_type = 6

COLOR.name = "Color"
COLOR.full_name = ".UnityEngine.Color"
COLOR.nested_types = {}
COLOR.enum_types = {}
COLOR.fields = {COLOR_R_FIELD, COLOR_G_FIELD, COLOR_B_FIELD, COLOR_A_FIELD}
COLOR.is_extendable = false
COLOR.extensions = {}

exports.MaterialData = protobuf.Message(MATERIALDATA)
exports.MeshData = protobuf.Message(MESHDATA)
exports.ModelData = protobuf.Message(MODELDATA)
exports.SubMesh = protobuf.Message(SUBMESH)

exports.Color = protobuf.Message(COLOR)
exports.Vector2 = protobuf.Message(VECTOR2)
exports.Vector3 = protobuf.Message(VECTOR3)

return exports

